//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantManagSyst.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngredientInventory
    {
        public int IngredientId { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> ReorderLevel { get; set; }
        public string SupplierInfo { get; set; }
    }
}
