//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantManagSyst.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItemIngredients
    {
        public int Id { get; set; }
        public int MenuItemId { get; set; }
        public int IngredientId { get; set; }
        public decimal QuantityRequired { get; set; }
    
        public virtual Ingredients Ingredients { get; set; }
        public virtual MenuItems MenuItems { get; set; }
    }
}
